---
title: "Mutual Information"
author: "Serena Leung"
date: "4/22/2022"
output: html_document
---
```{r}
library(readr)
library(tidyverse)
library(ggplot2)
NPD <- read_csv("NPD_clean.csv")
head(NPD)  
```


```{r}
NPD_group <- NPD %>% mutate(age_group = case_when(
        age >= 12 & age <= 28 ~ 1,
        age >= 29 & age <= 45 ~ 2,
        age >= 46 & age <= 53 ~ 3,
        age >= 54 & age <= 61 ~ 4,
        age >= 62 & age <= 65 ~ 5,
        age >= 66 & age <= 86 ~ 6), 
        
        score_group = case_when(
          score >= 0 & score <= 5 ~ 1,
          score >= 6 & score <= 14 ~ 2,
          score >= 15 & score <= 25 ~ 3,
          score >= 26 & score <= 32 ~ 4,
          score >= 33 & score <= 40 ~ 5))
```

Mutual Information 

$$I(Score, Q_i) = H(Score) - H(Score|Q_i) $$

Conditional Entropy
$$H(Score|Q_i) = -\sum p(Score, Q_i)logp(Score|Q_i) $$

Function to calculate conditional entropy
```{r}
# Function used inside main function 
# Calculating elements of the conditional matrix 
calc_cond <- function(i,j, joint_mt){
  # i = row, j = column 
  # dividing probability by total probability of that row
  return(joint_mt[i,j]/sum(joint_mt[i,]))
}


cond_entropy <- function(Qj){
  
  # H(Qi|Qj)

  # Selecting data from df and convert into a matrix
  count_mt <- NPD %>% 
    select(score, {{Qj}}) %>% 
    group_by(score, !!rlang::sym((Qj))) %>% 
    count() %>% 
    pivot_wider(names_from = score, values_from = n) %>% 
    replace(is.na(.), 0) %>%
    as.matrix()
  
  # Count matrix that contains counts of each subset
  count_mt <- count_mt[,-1]
 
  # Joint probability matrix
  joint_mt <- count_mt/sum(count_mt) 
  
  # Calculating elements of the conditional matrix 
  calc_cond <- function(i,j, joint_mt){
    # i = row, j = column 
    # dividing probability by total probability of that row
    return(joint_mt[i,j]/sum(joint_mt[i,]))
  }
  
  
  # Forming the conditional probablity matrix
  
  # Calculating the conditional probability values
  
  cond_prob_values <- c()
  
  for (response in c(1,2)) {  # either 0 or 1 response
    for (score_val in seq(1,40)) {
      cond_prob_values <- append(cond_prob_values, calc_cond(response, score_val, joint_mt))
    }
  }
  # Creating conditional probability matrix
  cond_mt <- matrix(cond_prob_values, byrow = TRUE, nrow = 2)
  
  
  # Calculating Conditional Entropy H(Q1|Q2 = 0)
  # given_0 <- -(joint_mt[1,1]*log2(cond_mt[1,1]) + joint_mt[1,2]*log2(cond_mt[1,2]))
  # 
  # given_1 <- -(joint_mt[2,1]*log2(cond_mt[2,1]) + joint_mt[2,2]*log2(cond_mt[2,2]))
  
  
  # Calculating Conditional Entropy 
  cond_entr_val <- 0
  
  for (response in c(1,2)) {  # either 0 or 1 response
    for (score_val in seq(1,40)) {
      # Sum all conditional entropies together
      cond_entr_val <- append(cond_entr_val, -(joint_mt[response, score_val]*log2(cond_mt[response, score_val])))
    }
  }
  
  return(list("Qj" = Qj, "count_mt" = count_mt, "joint_mt" = joint_mt, 
              "cond_mt" = cond_mt,
              "cond_entr" = sum(cond_entr_val, na.rm = TRUE)))
}


cond_entropy("Q2")

```



Testing (IT WORKS!!!)
```{r}

count_mt <- NPD %>% 
    select(score, Q2) %>% 
    group_by(score, Q2) %>% 
    count() %>% 
    pivot_wider(names_from = score, values_from = n) %>% 
    replace_na(list("0" = 0, "40" = 0)) %>%
    as.matrix()
  
  # Count matrix that contains counts of each subset
  count_mt <- count_mt[,-1]
  
count_mt
  
# Joint probability matrix
joint_mt <- count_mt/sum(count_mt) 
  
joint_mt  

# sum(joint_mt[2,]) 


# Create for loop that will calculate the conditional entropy values
cond_prob_values <- c()

for (response in c(1,2)) {  # either 0 or 1 response
  for (score_val in seq(1,40)) {
    cond_prob_values <- append(cond_prob_values, calc_cond(response, score_val, joint_mt))
  }
}

# cond_prob_values <- append(cond_prob_values, FALSE, after = 40)
# cond_prob_values  

# Forming the conditional matrix
cond_mt <- matrix(cond_prob_values, byrow = TRUE, nrow = 2)

cond_mt
  


value <- 0

for (response in c(1,2)) {  # either 0 or 1 response
  for (score_val in seq(1,40)) {
    # Sum all conditional entropies together
    value <- append(value, -(joint_mt[response, score_val]*log2(cond_mt[response, score_val])))
  }
}

# value

sum(value, na.rm = TRUE)

```




Score_group Entropy
```{r}
score_df <- NPD %>% select(score) %>% group_by(score) %>% count()

score_df 

#P(score)
p_score <- score_df$n/sum(score_df$n)

p_score

score_entropy <- -sum(p_score*log2(p_score))

score_entropy

```


```{r}
mutual_info <- data.frame(
  question = seq(1,40),
  score_entropy = rep(score_entropy, 40)
)


questions <- c(colnames(NPD_group)[2:41])
qi_cond <- c()


for (i in questions) {
  qi_cond <- append(qi_cond, cond_entropy(i)$cond_entr)
}

qi_cond

# Add qi_cond as another column, mutate to get I(x)
```


```{r}
# Add conditional entropy column
mutual_info["cond_entr"] <- qi_cond

mutual_info %>% mutate("mutual_info" = score_entropy - cond_entr) %>% arrange(desc(mutual_info))
```





